// Copyright (c) 2024 madalone. QML test harness for charging screen settings.
// SPDX-License-Identifier: GPL-3.0-or-later

// testdir.h MUST be included before <QtQuickTest> — the quicktest.h header
// uses #ifdef QUICK_TEST_SOURCE_DIR to select which macro variant to define.
#include "testdir.h"   // generated by qmake — defines QUICK_TEST_SOURCE_DIR

#include <QtQuickTest>
#include <QQmlEngine>
#include <QQmlContext>
#include <QColor>
#include <QFont>

#include "MockScreensaverConfig.h"
#include "MockHaptic.h"

// ── Mock objects (singleton lifetime) ──────────────────────────────
static MockScreensaverConfig *s_config = nullptr;
static MockHaptic *s_haptic = nullptr;

static QObject *configProvider(QQmlEngine *, QJSEngine *) {
    // QtQuick tests destroy/recreate the engine — prevent double-delete
    QQmlEngine::setObjectOwnership(s_config, QQmlEngine::CppOwnership);
    return s_config;
}
static QObject *hapticProvider(QQmlEngine *, QJSEngine *) {
    QQmlEngine::setObjectOwnership(s_haptic, QQmlEngine::CppOwnership);
    return s_haptic;
}

// ── Mock C++ object for fonts context property ────────────────────
// Mirrors uc::ui::Fonts — Q_INVOKABLE methods returning QFont
class MockFonts : public QObject {
    Q_OBJECT
 public:
    explicit MockFonts(QObject *parent = nullptr) : QObject(parent) {}

    Q_INVOKABLE QFont primaryFont(int size = 30, const QString &style = "Normal") {
        Q_UNUSED(style);
        QFont f("Helvetica");
        f.setPixelSize(size);
        return f;
    }
    Q_INVOKABLE QFont secondaryFont(int size = 24, const QString &style = "Normal") {
        Q_UNUSED(style);
        QFont f("Courier");
        f.setPixelSize(size);
        return f;
    }
    Q_INVOKABLE QFont primaryFontCapitalized(int size = 30, const QString &style = "Normal") {
        QFont f = primaryFont(size, style);
        f.setCapitalization(QFont::AllUppercase);
        return f;
    }
    Q_INVOKABLE QFont primaryFontCapitalizedFirst(int size = 30, const QString &style = "Normal") {
        QFont f = primaryFont(size, style);
        f.setCapitalization(QFont::Capitalize);
        return f;
    }
    Q_INVOKABLE QFont secondaryFontCapitalized(int size = 30, const QString &style = "Normal") {
        QFont f = secondaryFont(size, style);
        f.setCapitalization(QFont::AllUppercase);
        return f;
    }
    Q_INVOKABLE QFont secondaryFontCapitalizedFirst(int size = 30, const QString &style = "Normal") {
        QFont f = secondaryFont(size, style);
        f.setCapitalization(QFont::Capitalize);
        return f;
    }
};

// ── Mock C++ object for colors context property ───────────────────
// Mirrors uc::ui::Colors — all are constant QColor members
class MockColors : public QObject {
    Q_OBJECT
    Q_PROPERTY(QColor white MEMBER white CONSTANT)
    Q_PROPERTY(QColor offwhite MEMBER offwhite CONSTANT)
    Q_PROPERTY(QColor black MEMBER black CONSTANT)
    Q_PROPERTY(QColor transparent MEMBER transparent CONSTANT)
    Q_PROPERTY(QColor light MEMBER light CONSTANT)
    Q_PROPERTY(QColor medium MEMBER medium CONSTANT)
    Q_PROPERTY(QColor dark MEMBER dark CONSTANT)
    Q_PROPERTY(QColor highlight MEMBER highlight CONSTANT)
    Q_PROPERTY(QColor red MEMBER red CONSTANT)
    Q_PROPERTY(QColor green MEMBER green CONSTANT)
    Q_PROPERTY(QColor orange MEMBER orange CONSTANT)
    Q_PROPERTY(QColor yellow MEMBER yellow CONSTANT)
    Q_PROPERTY(QColor blue MEMBER blue CONSTANT)
    Q_PROPERTY(QColor primaryButton MEMBER primaryButton CONSTANT)
    Q_PROPERTY(QColor secondaryButton MEMBER secondaryButton CONSTANT)

 public:
    explicit MockColors(QObject *parent = nullptr) : QObject(parent) {}

    QColor white{QColor("#FFFFFF")};
    QColor offwhite{QColor("#d0d0d0")};
    QColor black{QColor("#000000")};
    QColor transparent{QColor(Qt::transparent)};
    QColor light{QColor("#888888")};
    QColor medium{QColor("#444444")};
    QColor dark{QColor("#222222")};
    QColor highlight{QColor("#00aaff")};
    QColor red{QColor("#ff3e54")};
    QColor green{QColor("#769990")};
    QColor orange{QColor("#FF7241")};
    QColor yellow{QColor("#ffe78a")};
    QColor blue{QColor("#335266")};
    QColor primaryButton{QColor("#555555")};
    QColor secondaryButton{QColor("#333333")};
};

// ── Mock C++ object for ui context property ───────────────────────
// Mirrors uc::ui::UiController — the subset referenced by settings components
class MockUi : public QObject {
    Q_OBJECT
    Q_PROPERTY(int width READ width CONSTANT)
    Q_PROPERTY(int height READ height CONSTANT)
    Q_PROPERTY(bool keyNavigationEnabled READ keyNavigationEnabled CONSTANT)
    Q_PROPERTY(int cornerRadiusSmall READ cornerRadiusSmall CONSTANT)
    Q_PROPERTY(int cornerRadiusLarge READ cornerRadiusLarge CONSTANT)
    Q_PROPERTY(double ratio READ ratio CONSTANT)
    Q_PROPERTY(QObject* inputController READ inputController CONSTANT)

 public:
    explicit MockUi(QObject *parent = nullptr)
        : QObject(parent), m_inputController(new QObject(this)) {}

    int width() const { return 480; }
    int height() const { return 850; }
    bool keyNavigationEnabled() const { return true; }
    int cornerRadiusSmall() const { return 4; }
    int cornerRadiusLarge() const { return 8; }
    double ratio() const { return 1.0; }
    QObject* inputController() const { return m_inputController; }

 private:
    QObject *m_inputController;
};

// ── Mock C++ object for resource context property ─────────────────
class MockResource : public QObject {
    Q_OBJECT
 public:
    explicit MockResource(QObject *parent = nullptr) : QObject(parent) {}
    Q_INVOKABLE QString getIcon(const QString &, const QString & = QString()) { return ""; }
};

// ── Setup class for QUICK_TEST_MAIN_WITH_SETUP ────────────────────
class Setup : public QObject {
    Q_OBJECT

 public slots:
    void applicationAvailable() {
        s_config = new MockScreensaverConfig;
        s_haptic = new MockHaptic;
        qmlRegisterSingletonType<MockScreensaverConfig>("ScreensaverConfig", 1, 0, "ScreensaverConfig", configProvider);
        qmlRegisterSingletonType<MockHaptic>("Haptic", 1, 0, "Haptic", hapticProvider);
    }

    void qmlEngineAvailable(QQmlEngine *engine) {
        auto *ctx = engine->rootContext();

        // Context property mocks matching src/ui/uiController.cpp setup
        ctx->setContextProperty("colors", new MockColors(engine));
        ctx->setContextProperty("fonts", new MockFonts(engine));
        ctx->setContextProperty("ui", new MockUi(engine));
        ctx->setContextProperty("resource", new MockResource(engine));

        // keyboard / keyboardInputField — needed by InputField.qml
        // Stub with a QObject that has show()/hide() methods via QML
        auto *keyboard = new QObject(engine);
        ctx->setContextProperty("keyboard", keyboard);
        ctx->setContextProperty("keyboardInputField", keyboard);

        // profileRoot — needed by Settings.Page for goBack/goHome
        auto *profileRoot = new QObject(engine);
        profileRoot->setProperty("goBack", QVariant());
        profileRoot->setProperty("goHome", QVariant());
        ctx->setContextProperty("profileRoot", profileRoot);

        // Add test/qml directory to the import path for local test QML files
        engine->addImportPath(QStringLiteral(QUICK_TEST_SOURCE_DIR));
    }

    void cleanupTestCase() {
        // Singletons are C++ owned — clean up manually
        delete s_config; s_config = nullptr;
        delete s_haptic; s_haptic = nullptr;
    }
};

QUICK_TEST_MAIN_WITH_SETUP(testQml, Setup)

#include "tst_qml_main.moc"
