// Copyright (c) 2026 madalone. Mock core::Api impl for unit testing Mod 5/6 hardware components.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file provides linker symbols for the methods of `uc::core::Api` that the
// hardware components under test (ActivitySessionKeeper, PhantomWakeSuppressor)
// actually call. Methods that are declared in core.h but never invoked by the
// keeper/suppressor are NOT defined here — if a future test path adds a new
// API call, the linker will tell us what's missing.
//
// Critical methods replicated from production `src/core/core.cpp`:
//   - Api::Api(url, parent)        — minimal init, no WebSocket open, m_connected=true
//   - Api::~Api()                  — no-op
//   - Api::setPowerMode(mode)      — VERBATIM mirror of core.cpp:819-823 (the v1.4.22 fix line)
//   - Api::sendRequest(type, msg)  — VERBATIM mirror of core.cpp:113-140 (constructs JSON envelope)
//   - Api::sendMessage(message)    — no-op stub returning true
//   - Api::setupTimerForRequest    — no-op stub
//   - Api::removeRequestTimer      — no-op stub
//
// All MOC-generated code for `Api` (signal emit functions, qt_metacall, etc.) is
// auto-generated by qmake from the real `core.h` and is NOT in this file.
//
// REGRESSION-PREVENTION CONTRACT: the body construction in setPowerMode below must
// stay byte-identical to core.cpp:819-823. If a future code change to either side
// drifts away from `msgData.insert("mode", ...)`, both sides MUST be updated and
// the test must be re-aligned.

#include <QCoreApplication>
#include <QJsonDocument>
#include <QString>
#include <QVariantMap>

#include "../../src/core/core.h"
#include "../../src/util.h"
#include "mock_core_api.h"

namespace uc {
namespace test {

// Recorder state — module-local, accessed via MockCoreRecorder static interface.
namespace {
int         g_setPowerModeCallCount = 0;
QString     g_lastPowerModeValue;
QVariantMap g_lastSentMsgData;
QString     g_lastSentRequestJson;
bool        g_connected = true;  // default: keep "connected" so sendRequest doesn't early-return
}  // namespace

void MockCoreRecorder::reset() {
    g_setPowerModeCallCount = 0;
    g_lastPowerModeValue.clear();
    g_lastSentMsgData.clear();
    g_lastSentRequestJson.clear();
    g_connected = true;
}

int MockCoreRecorder::setPowerModeCallCount() {
    return g_setPowerModeCallCount;
}

QString MockCoreRecorder::lastPowerModeValue() {
    return g_lastPowerModeValue;
}

QVariantMap MockCoreRecorder::lastSentMsgData() {
    return g_lastSentMsgData;
}

QString MockCoreRecorder::lastSentRequestJson() {
    return g_lastSentRequestJson;
}

void MockCoreRecorder::setConnected(bool connected) {
    g_connected = connected;
}

bool MockCoreRecorder::isConnected() {
    return g_connected;
}

}  // namespace test
}  // namespace uc

// ──────────────────────────────────────────────────────────────────────────────
// uc::core::Api stub implementations.
// Real impls live in src/core/core.cpp — these mirror them at the body-shape level
// to keep the keeper/suppressor's call paths exercised end-to-end with no live
// WebSocket dep. See file header comment for the regression-prevention contract.
// ──────────────────────────────────────────────────────────────────────────────

namespace uc {
namespace core {

Api::Api(const QString& url, QObject* parent) : QObject(parent), m_url(url) {
    // Production ctor opens a real QWebSocket and starts keepalive/reconnect timers.
    // Stub ctor: no WebSocket activity, but force m_connected so sendRequest() runs
    // its full body-construction path (so the test can inspect the assembled message).
    m_connected = uc::test::MockCoreRecorder::isConnected();
    m_requestId = 0;

    // Production ctor also creates m_keepAliveTimer / m_reconnectTimer. The destructor
    // doesn't touch them, but creating them avoids any UB if some path reads m_*Timer
    // pointers before our test exits. Allocate them as no-op QTimers.
    m_keepAliveTimer  = new QTimer(this);
    m_reconnectTimer  = new QTimer(this);
    m_requestTimeout  = 10000;
}

Api::~Api() = default;

void Api::connect() {
    // No-op stub — real impl opens QWebSocket; we don't need a network round-trip.
}

void Api::disconnect() {
    // No-op stub — real impl closes QWebSocket.
}

bool Api::sendMessage(const QString& message) {
    // Production impl: m_webSocket.sendTextMessage(message) > 0
    // Stub records the message (already captured upstream in sendRequest) and
    // reports success so sendRequest() returns a valid request id.
    Q_UNUSED(message)
    return true;
}

// VERBATIM MIRROR of core.cpp:113-140 — request envelope construction.
// MUST stay in lockstep with production. See file header for regression policy.
int Api::sendRequest(RequestTypes::Enum type, const QVariantMap msgData) {
    if (!m_connected && type != RequestTypes::auth) {
        return -1;
    }

    m_requestId++;
    unsigned int id = m_requestId;

    QVariantMap map;
    map.insert("kind", "req");
    map.insert("id", id);
    map.insert("msg", uc::Util::convertEnumToString(type));
    map.insert("msg_data", msgData);

    QJsonDocument doc     = QJsonDocument::fromVariant(map);
    QString       message = doc.toJson(QJsonDocument::JsonFormat::Compact);

    // Test instrumentation: capture the assembled outgoing JSON for later inspection.
    uc::test::g_lastSentRequestJson = message;
    uc::test::g_lastSentMsgData     = msgData;

    if (sendMessage(message)) {
        setupTimerForRequest(id);
        return static_cast<int>(id);
    } else {
        return -1;
    }
}

// VERBATIM MIRROR of core.cpp:819-823 — the v1.4.22 fix line is `msgData.insert("mode", ...)`.
// If you change this, you MUST update core.cpp AND keep the test assertions aligned.
int Api::setPowerMode(PowerEnums::PowerMode mode) {
    QVariantMap msgData;
    msgData.insert("mode", uc::Util::convertEnumToString(mode));

    // Test instrumentation: track call count and the field value the keeper/suppressor sent.
    uc::test::g_setPowerModeCallCount++;
    uc::test::g_lastPowerModeValue = msgData.value("mode").toString();

    return sendRequest(RequestTypes::set_power_mode, msgData);
}

// ──────────────────────────────────────────────────────────────────────────────
// Methods below are unused by keeper/suppressor but must be present for linker
// resolution if MOC-generated code references them. Add new no-op stubs here as
// new test paths surface link errors.
// ──────────────────────────────────────────────────────────────────────────────

void Api::setupTimerForRequest(int requestId) {
    Q_UNUSED(requestId)
    // Real impl creates QTimer for response timeout tracking. Test path doesn't
    // wait on responses, so this is a no-op.
}

void Api::removeRequestTimer(int requestId) {
    Q_UNUSED(requestId)
    // Real impl cleans up timer when response arrives. No-op in stub.
}

void Api::onTextMessageReceived(const QString& message) {
    Q_UNUSED(message)
}

void Api::onStateChanged(QAbstractSocket::SocketState state) {
    Q_UNUSED(state)
}

void Api::onError(QAbstractSocket::SocketError error) {
    Q_UNUSED(error)
}

void Api::onKeepAliveTimerTimeout() {}
void Api::startKeepAliveTimer() {}
void Api::stopKeepAliveTimer() {}
void Api::onReconnectTimerTimeout() {}

}  // namespace core
}  // namespace uc
