// Copyright (c) 2026 madalone. Mock core::Api impl for unit testing Mod 5/6 hardware components.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file provides linker symbols for the methods of `uc::core::Api` that the
// hardware components under test (ActivitySessionKeeper, PhantomWakeSuppressor)
// actually call. Methods that are declared in core.h but never invoked by the
// keeper/suppressor are NOT defined here — if a future test path adds a new
// API call, the linker will tell us what's missing.
//
// Critical methods replicated from production `src/core/core.cpp`:
//   - Api::Api(url, parent)        — minimal init, no WebSocket open, m_connected=true
//   - Api::~Api()                  — no-op
//   - Api::setPowerMode(mode)      — VERBATIM mirror of core.cpp:819-823 (the v1.4.22 fix line)
//   - Api::sendRequest(type, msg)  — VERBATIM mirror of core.cpp:113-140 (constructs JSON envelope)
//   - Api::sendMessage(message)    — no-op stub returning true
//   - Api::setupTimerForRequest    — no-op stub
//   - Api::removeRequestTimer      — no-op stub
//
// All MOC-generated code for `Api` (signal emit functions, qt_metacall, etc.) is
// auto-generated by qmake from the real `core.h` and is NOT in this file.
//
// REGRESSION-PREVENTION CONTRACT: the body construction in setPowerMode below must
// stay byte-identical to core.cpp:819-823. If a future code change to either side
// drifts away from `msgData.insert("mode", ...)`, both sides MUST be updated and
// the test must be re-aligned.

#include <QCoreApplication>
#include <QJsonDocument>
#include <QList>
#include <QQueue>
#include <QString>
#include <QTimer>
#include <QVariantMap>

#include "../../src/core/core.h"
#include "../../src/util.h"
#include "mock_core_api.h"

namespace uc {
namespace test {

// Recorder state — module-local, accessed via MockCoreRecorder static interface.
namespace {
int         g_setPowerModeCallCount = 0;
QString     g_lastPowerModeValue;
QVariantMap g_lastSentMsgData;
QString     g_lastSentRequestJson;
bool        g_connected = true;  // default: keep "connected" so sendRequest doesn't early-return

// M1: standby_inhibitors recording.
int     g_createInhibitorCallCount = 0;
QString g_lastInhibitorWho;
QString g_lastInhibitorWhy;
int     g_lastInhibitorDelay = -1;
int     g_deleteInhibitorCallCount = 0;
QString g_lastDeletedInhibitorId;
int     g_listInhibitorsCallCount = 0;

// M1: queued responses. Tests push the response the next call should emit.
struct CreateResp { int httpCode; QString id; QString errorMessage; };
struct DeleteResp { int httpCode; QString errorMessage; };
struct ListResp   { int httpCode; QList<uc::core::Inhibitor> inhibitors; QString errorMessage; };
QQueue<CreateResp> g_pendingCreateResponses;
QQueue<DeleteResp> g_pendingDeleteResponses;
QQueue<ListResp>   g_pendingListResponses;
}  // namespace

void MockCoreRecorder::reset() {
    g_setPowerModeCallCount = 0;
    g_lastPowerModeValue.clear();
    g_lastSentMsgData.clear();
    g_lastSentRequestJson.clear();
    g_connected = true;
    // M1
    g_createInhibitorCallCount = 0;
    g_lastInhibitorWho.clear();
    g_lastInhibitorWhy.clear();
    g_lastInhibitorDelay = -1;
    g_deleteInhibitorCallCount = 0;
    g_lastDeletedInhibitorId.clear();
    g_listInhibitorsCallCount = 0;
    g_pendingCreateResponses.clear();
    g_pendingDeleteResponses.clear();
    g_pendingListResponses.clear();
}

int MockCoreRecorder::setPowerModeCallCount() {
    return g_setPowerModeCallCount;
}

QString MockCoreRecorder::lastPowerModeValue() {
    return g_lastPowerModeValue;
}

QVariantMap MockCoreRecorder::lastSentMsgData() {
    return g_lastSentMsgData;
}

QString MockCoreRecorder::lastSentRequestJson() {
    return g_lastSentRequestJson;
}

void MockCoreRecorder::setConnected(bool connected) {
    g_connected = connected;
}

bool MockCoreRecorder::isConnected() {
    return g_connected;
}

// ──────────────────────────────────────────────────────────────────────────
// M1 (2026-05-03): standby_inhibitors recorder accessors + response injection.
// ──────────────────────────────────────────────────────────────────────────
int     MockCoreRecorder::createInhibitorCallCount() { return g_createInhibitorCallCount; }
QString MockCoreRecorder::lastInhibitorWho() { return g_lastInhibitorWho; }
QString MockCoreRecorder::lastInhibitorWhy() { return g_lastInhibitorWhy; }
int     MockCoreRecorder::lastInhibitorDelay() { return g_lastInhibitorDelay; }
int     MockCoreRecorder::deleteInhibitorCallCount() { return g_deleteInhibitorCallCount; }
QString MockCoreRecorder::lastDeletedInhibitorId() { return g_lastDeletedInhibitorId; }
int     MockCoreRecorder::listInhibitorsCallCount() { return g_listInhibitorsCallCount; }

void MockCoreRecorder::pushNextCreateResponse(int httpCode, const QString& id, const QString& errorMessage) {
    g_pendingCreateResponses.enqueue({httpCode, id, errorMessage});
}
void MockCoreRecorder::pushNextDeleteResponse(int httpCode, const QString& errorMessage) {
    g_pendingDeleteResponses.enqueue({httpCode, errorMessage});
}
void MockCoreRecorder::pushNextListResponse(int httpCode, const QList<uc::core::Inhibitor>& inhibitors,
                                            const QString& errorMessage) {
    g_pendingListResponses.enqueue({httpCode, inhibitors, errorMessage});
}

}  // namespace test
}  // namespace uc

// ──────────────────────────────────────────────────────────────────────────────
// uc::core::Api stub implementations.
// Real impls live in src/core/core.cpp — these mirror them at the body-shape level
// to keep the keeper/suppressor's call paths exercised end-to-end with no live
// WebSocket dep. See file header comment for the regression-prevention contract.
// ──────────────────────────────────────────────────────────────────────────────

namespace uc {
namespace core {

Api::Api(const QString& url, QObject* parent) : QObject(parent), m_url(url) {
    // Production ctor opens a real QWebSocket and starts keepalive/reconnect timers.
    // Stub ctor: no WebSocket activity, but force m_connected so sendRequest() runs
    // its full body-construction path (so the test can inspect the assembled message).
    m_connected = uc::test::MockCoreRecorder::isConnected();
    m_requestId = 0;

    // Production ctor also creates m_keepAliveTimer / m_reconnectTimer. The destructor
    // doesn't touch them, but creating them avoids any UB if some path reads m_*Timer
    // pointers before our test exits. Allocate them as no-op QTimers.
    m_keepAliveTimer  = new QTimer(this);
    m_reconnectTimer  = new QTimer(this);
    m_requestTimeout  = 10000;
}

Api::~Api() = default;

void Api::connect() {
    // No-op stub — real impl opens QWebSocket; we don't need a network round-trip.
}

void Api::disconnect() {
    // No-op stub — real impl closes QWebSocket.
}

bool Api::sendMessage(const QString& message) {
    // Production impl: m_webSocket.sendTextMessage(message) > 0
    // Stub records the message (already captured upstream in sendRequest) and
    // reports success so sendRequest() returns a valid request id.
    Q_UNUSED(message)
    return true;
}

// VERBATIM MIRROR of core.cpp:113-140 — request envelope construction.
// MUST stay in lockstep with production. See file header for regression policy.
int Api::sendRequest(RequestTypes::Enum type, const QVariantMap msgData) {
    if (!m_connected && type != RequestTypes::auth) {
        return -1;
    }

    m_requestId++;
    unsigned int id = m_requestId;

    QVariantMap map;
    map.insert("kind", "req");
    map.insert("id", id);
    map.insert("msg", uc::Util::convertEnumToString(type));
    map.insert("msg_data", msgData);

    QJsonDocument doc     = QJsonDocument::fromVariant(map);
    QString       message = doc.toJson(QJsonDocument::JsonFormat::Compact);

    // Test instrumentation: capture the assembled outgoing JSON for later inspection.
    uc::test::g_lastSentRequestJson = message;
    uc::test::g_lastSentMsgData     = msgData;

    if (sendMessage(message)) {
        setupTimerForRequest(id);
        return static_cast<int>(id);
    } else {
        return -1;
    }
}

// VERBATIM MIRROR of core.cpp:819-823 — the v1.4.22 fix line is `msgData.insert("mode", ...)`.
// If you change this, you MUST update core.cpp AND keep the test assertions aligned.
int Api::setPowerMode(PowerEnums::PowerMode mode) {
    QVariantMap msgData;
    msgData.insert("mode", uc::Util::convertEnumToString(mode));

    // Test instrumentation: track call count and the field value the keeper/suppressor sent.
    uc::test::g_setPowerModeCallCount++;
    uc::test::g_lastPowerModeValue = msgData.value("mode").toString();

    return sendRequest(RequestTypes::set_power_mode, msgData);
}

// ──────────────────────────────────────────────────────────────────────────────
// Methods below are unused by keeper/suppressor but must be present for linker
// resolution if MOC-generated code references them. Add new no-op stubs here as
// new test paths surface link errors.
// ──────────────────────────────────────────────────────────────────────────────

// EntityController test (resume-window state machine): EntityController's metaobject references
// these entity/media Api methods via its slots, so they must resolve at link even though the
// onPowerModeChanged path under test never calls them. No-op stubs (return -1 = invalid request id).
int Api::getEntity(const QString&) { return -1; }
int Api::getEntities(int, int, EntityFilter) { return -1; }
int Api::getAvailableEntities(int, int, bool, AvailableEntitiesFilter) { return -1; }
int Api::configureEntities(const QString&, const QStringList&) { return -1; }
int Api::updateEntity(const QString&, QVariantMap, const QString&) { return -1; }
int Api::deleteEntities(const QStringList&, const QString&) { return -1; }
int Api::entityCommand(const QString&, const QString&, QVariantMap) { return -1; }
int Api::browseMedia(const QString&, QVariantMap) { return -1; }
int Api::searchMedia(const QString&, QVariantMap) { return -1; }

void Api::setupTimerForRequest(int requestId) {
    Q_UNUSED(requestId)
    // Real impl creates QTimer for response timeout tracking. Test path doesn't
    // wait on responses, so this is a no-op.
}

void Api::removeRequestTimer(int requestId) {
    Q_UNUSED(requestId)
    // Real impl cleans up timer when response arrives. No-op in stub.
}

void Api::onTextMessageReceived(const QString& message) {
    Q_UNUSED(message)
}

void Api::onStateChanged(QAbstractSocket::SocketState state) {
    Q_UNUSED(state)
}

void Api::onError(QAbstractSocket::SocketError error) {
    Q_UNUSED(error)
}

void Api::onKeepAliveTimerTimeout() {}
void Api::startKeepAliveTimer() {}
void Api::stopKeepAliveTimer() {}
void Api::onReconnectTimerTimeout() {}

// ──────────────────────────────────────────────────────────────────────────
// M1 (2026-05-03): standby_inhibitors REST stubs.
//
// Each stub records args + emits the corresponding resp* signal on the next
// event loop iteration via QTimer::singleShot(0, this, ...). This matches the
// production async behavior (QNetworkReply::finished is async) so the keeper's
// `auto* conn = new QMetaObject::Connection; *conn = QObject::connect(...)`
// pattern (which sets up the connection AFTER the call) works correctly.
//
// Tests must call QCoreApplication::processEvents() (or QTest::qWait(0)) after
// triggering a keeper edge to let the queued emit fire.
//
// Default response shape if test forgot to push: 201/{id="mock-uuid"} for create,
// 200 for delete, 200/[] for list. Forces test failures to be obvious (a real
// regression is more likely to be "wrong field" than "no response").
// ──────────────────────────────────────────────────────────────────────────

int Api::createStandbyInhibitor(const QString& who, const QString& why, int delaySec) {
    uc::test::g_createInhibitorCallCount++;
    uc::test::g_lastInhibitorWho   = who;
    uc::test::g_lastInhibitorWhy   = why;
    uc::test::g_lastInhibitorDelay = delaySec;

    const int reqId = static_cast<int>(++m_restRequestId);

    int     httpCode     = 201;
    QString id           = QStringLiteral("mock-uuid");
    QString errorMessage;
    if (!uc::test::g_pendingCreateResponses.isEmpty()) {
        const auto r = uc::test::g_pendingCreateResponses.dequeue();
        httpCode     = r.httpCode;
        id           = r.id;
        errorMessage = r.errorMessage;
    }

    QTimer::singleShot(0, this, [this, reqId, httpCode, id, errorMessage]() {
        emit respCreateInhibitor(reqId, httpCode, id, errorMessage);
    });
    return reqId;
}

int Api::deleteStandbyInhibitor(const QString& id) {
    uc::test::g_deleteInhibitorCallCount++;
    uc::test::g_lastDeletedInhibitorId = id;

    const int reqId = static_cast<int>(++m_restRequestId);

    int     httpCode = 200;
    QString errorMessage;
    if (!uc::test::g_pendingDeleteResponses.isEmpty()) {
        const auto r = uc::test::g_pendingDeleteResponses.dequeue();
        httpCode     = r.httpCode;
        errorMessage = r.errorMessage;
    }

    QTimer::singleShot(0, this, [this, reqId, httpCode, errorMessage]() {
        emit respDeleteInhibitor(reqId, httpCode, errorMessage);
    });
    return reqId;
}

int Api::listStandbyInhibitors() {
    uc::test::g_listInhibitorsCallCount++;

    const int reqId = static_cast<int>(++m_restRequestId);

    int                        httpCode = 200;
    QList<uc::core::Inhibitor> inhibitors;
    QString                    errorMessage;
    if (!uc::test::g_pendingListResponses.isEmpty()) {
        const auto r = uc::test::g_pendingListResponses.dequeue();
        httpCode     = r.httpCode;
        inhibitors   = r.inhibitors;
        errorMessage = r.errorMessage;
    }

    QTimer::singleShot(0, this, [this, reqId, httpCode, inhibitors, errorMessage]() {
        emit respListInhibitors(reqId, httpCode, inhibitors, errorMessage);
    });
    return reqId;
}

// madalone (Phase 0): Q_INVOKABLE void Api::probeRestAuth() declaration in core.h
// generates a moc metacall stub that the test binary links. The keeper/suppressor
// don't call probeRestAuth, but moc resolves the symbol regardless — without this
// no-op stub the test binary fails to link with `undefined reference to
// 'uc::core::Api::probeRestAuth()'`. CI Hardware-tests caught this on the v1.4.39
// push (Phase 0 was local-only-build per audit Q2 so it never went through CI).
void Api::probeRestAuth() {
    // intentionally no-op: probe is a one-shot diagnostic gated on Config.probeRestAuth;
    // unit tests don't exercise it.
}

}  // namespace core
}  // namespace uc
