// Copyright (c) 2026 madalone. Integration test harness for MatrixRainItem.
// Tests the real renderer in a QQuickWindow with OpenGL context — no mocks.
// SPDX-License-Identifier: GPL-3.0-or-later

// testdir.h MUST be included before <QtQuickTest> — the quicktest.h header
// uses #ifdef QUICK_TEST_SOURCE_DIR to select which macro variant to define.
#include "testdir.h"   // generated by qmake — defines QUICK_TEST_SOURCE_DIR

#include <QtQuickTest>
#include <QQmlEngine>
#include <QQmlContext>
#include "ui/matrixrain.h"
// Minimal ScreensaverConfig stub for integration tests.
// The real ScreensaverConfig pulls in Battery → Core → QWebSocket and
// requires MOC for Battery signals. Instead, register a bare QObject
// as the "ScreensaverConfig" QML singleton with default property values.
#include <QSettings>

class StubScreensaverConfig : public QObject {
    Q_OBJECT
    // Only the properties referenced by integration test QML files
    Q_PROPERTY(qreal speed READ speed CONSTANT)
    Q_PROPERTY(qreal density READ density CONSTANT)
    Q_PROPERTY(qreal fadeRate READ fadeRate CONSTANT)
    Q_PROPERTY(int trailLength READ trailLength CONSTANT)
    Q_PROPERTY(int fontSize READ fontSize CONSTANT)
    Q_PROPERTY(QString colorMode READ colorMode CONSTANT)
    Q_PROPERTY(QString charset READ charset CONSTANT)
    Q_PROPERTY(int matrixSpeed READ matrixSpeed CONSTANT)
    Q_PROPERTY(int matrixDensity READ matrixDensity CONSTANT)
    Q_PROPERTY(int matrixFade READ matrixFade CONSTANT)
    Q_PROPERTY(int matrixTrail READ matrixTrail CONSTANT)
public:
    explicit StubScreensaverConfig(QObject *p = nullptr) : QObject(p) {}
    qreal speed() const { return 1.0; }
    qreal density() const { return 0.7; }
    qreal fadeRate() const { return 0.88; }
    int trailLength() const { return 50; }
    int fontSize() const { return 16; }
    QString colorMode() const { return "green"; }
    QString charset() const { return "ascii"; }
    int matrixSpeed() const { return 50; }
    int matrixDensity() const { return 70; }
    int matrixFade() const { return 60; }
    int matrixTrail() const { return 50; }
};

static StubScreensaverConfig *s_stubConfig = nullptr;
static QObject *stubConfigProvider(QQmlEngine *e, QJSEngine *) {
    e->setObjectOwnership(s_stubConfig, QQmlEngine::CppOwnership);
    return s_stubConfig;
}

class Setup : public QObject {
    Q_OBJECT
public slots:
    void applicationAvailable() {
        qmlRegisterType<MatrixRainItem>("MatrixRain", 1, 0, "MatrixRain");
        s_stubConfig = new StubScreensaverConfig(qApp);
        qmlRegisterSingletonType<StubScreensaverConfig>(
            "ScreensaverConfig", 1, 0, "ScreensaverConfig", stubConfigProvider);
    }
    void qmlEngineAvailable(QQmlEngine *engine) {
        Q_UNUSED(engine);
        // No context mocks needed — integration tests exercise the real renderer
        // through the public Q_PROPERTY API only. The MatrixRainItem doesn't
        // reference fonts/colors/ui context properties.
    }
};

QUICK_TEST_MAIN_WITH_SETUP(testIntegration, Setup)
#include "tst_integration_main.moc"
