// Copyright (c) 2024 madalone. Integration test harness for MatrixRainItem.
// Tests the real renderer in a QQuickWindow with OpenGL context — no mocks.
// SPDX-License-Identifier: GPL-3.0-or-later

// testdir.h MUST be included before <QtQuickTest> — the quicktest.h header
// uses #ifdef QUICK_TEST_SOURCE_DIR to select which macro variant to define.
#include "testdir.h"   // generated by qmake — defines QUICK_TEST_SOURCE_DIR

#include <QtQuickTest>
#include <QQmlEngine>
#include <QQmlContext>
#include "ui/matrixrain.h"

class Setup : public QObject {
    Q_OBJECT
public slots:
    void applicationAvailable() {
        qmlRegisterType<MatrixRainItem>("MatrixRain", 1, 0, "MatrixRain");
    }
    void qmlEngineAvailable(QQmlEngine *engine) {
        Q_UNUSED(engine);
        // No context mocks needed — integration tests exercise the real renderer
        // through the public Q_PROPERTY API only. The MatrixRainItem doesn't
        // reference fonts/colors/ui context properties.
    }
};

QUICK_TEST_MAIN_WITH_SETUP(testIntegration, Setup)
#include "tst_integration_main.moc"
